version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${SNOTIFY_RABBIT_API_PORT}:5672
      - ${SNOTIFY_RABBIT_ADMIN_PORT}:15672

  elasticsearch:
    image: elasticsearch:5.1.2
    ports:
      - ${SNOTIFY_ES_HTTP_PORT}:9200
    environment:
      discovery.type: single-node

  kibana:
    image: kibana:5
    ports:
      - ${SNOTIFY_KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    depends_on:
      - elasticsearch
